export type ContentFieldType = "text" | "textarea" | "list";

export type ContentField = {
  key: string;
  label: string;
  type: ContentFieldType;
  defaultValue: string;
};

export const GOOGLE_FONTS = [
  { name: "Inter", category: "sans-serif" },
  { name: "Plus Jakarta Sans", category: "sans-serif" },
  { name: "Poppins", category: "sans-serif" },
  { name: "DM Sans", category: "sans-serif" },
  { name: "Space Grotesk", category: "sans-serif" },
  { name: "Montserrat", category: "sans-serif" },
  { name: "Raleway", category: "sans-serif" },
  { name: "Open Sans", category: "sans-serif" },
  { name: "Playfair Display", category: "serif" },
  { name: "Lora", category: "serif" },
  { name: "Merriweather", category: "serif" },
];

export const GOOGLE_FONTS_URL =
  "https://fonts.googleapis.com/css2?" +
  [
    "family=Inter:wght@400;500;600;700",
    "family=Plus+Jakarta+Sans:wght@400;500;600;700",
    "family=Poppins:wght@400;500;600;700",
    "family=DM+Sans:wght@400;500;600;700",
    "family=Space+Grotesk:wght@400;500;600;700",
    "family=Montserrat:wght@400;500;600;700",
    "family=Raleway:wght@400;500;600;700",
    "family=Open+Sans:wght@400;500;600;700",
    "family=Playfair+Display:wght@400;500;600;700",
    "family=Lora:wght@400;500;600;700",
    "family=Merriweather:wght@400;700",
  ].join("&") +
  "&display=swap";

export const variantContentSchemas: Record<string, ContentField[]> = {
  "nav-a": [
    { key: "logo", label: "Logo Text", type: "text", defaultValue: "Logo" },
    { key: "links", label: "Nav Links", type: "list", defaultValue: "Home, About, Work, Contact" },
    { key: "ctaText", label: "Button Text", type: "text", defaultValue: "Get Started" },
  ],
  "nav-b": [
    { key: "logo", label: "Logo Text", type: "text", defaultValue: "LOGO" },
    { key: "links", label: "Nav Links", type: "list", defaultValue: "Home, About, Services, Work, Contact" },
  ],
  "hero-a": [
    { key: "heading", label: "Heading", type: "textarea", defaultValue: "Build beautiful websites\nwithout the complexity" },
    { key: "subheading", label: "Subheading", type: "textarea", defaultValue: "A modern, intuitive web builder that lets you bring your vision to life with zero friction." },
    { key: "primaryBtn", label: "Primary Button", type: "text", defaultValue: "Start Building" },
    { key: "secondaryBtn", label: "Secondary Button", type: "text", defaultValue: "Learn More" },
  ],
  "hero-b": [
    { key: "label", label: "Label", type: "text", defaultValue: "Welcome" },
    { key: "heading", label: "Heading", type: "textarea", defaultValue: "We craft digital\nexperiences that matter" },
    { key: "subheading", label: "Subheading", type: "textarea", defaultValue: "Strategy, design and technology — fused into seamless products people love to use." },
    { key: "primaryBtn", label: "Button Text", type: "text", defaultValue: "View Our Work" },
  ],
  "hero-c": [
    { key: "word1", label: "Word 1", type: "text", defaultValue: "SOFTWARE" },
    { key: "word2", label: "Word 2", type: "text", defaultValue: "SOLUTIONS" },
    { key: "description", label: "Description", type: "textarea", defaultValue: "We design, develop, and deploy scalable digital products that help companies grow faster and operate smarter." },
    { key: "ctaText", label: "CTA Text", type: "text", defaultValue: "Explore More" },
  ],
  "features-a": [
    { key: "title", label: "Section Title", type: "text", defaultValue: "Features" },
    { key: "subtitle", label: "Subtitle", type: "text", defaultValue: "Everything you need to build a standout website." },
    { key: "card1Title", label: "Card 1 Title", type: "text", defaultValue: "Lightning Fast" },
    { key: "card1Desc", label: "Card 1 Description", type: "textarea", defaultValue: "Optimised performance out of the box with near-instant load times." },
    { key: "card2Title", label: "Card 2 Title", type: "text", defaultValue: "Pixel Perfect" },
    { key: "card2Desc", label: "Card 2 Description", type: "textarea", defaultValue: "Every element is crafted to be crisp and precise on any screen size." },
    { key: "card3Title", label: "Card 3 Title", type: "text", defaultValue: "Fully Responsive" },
    { key: "card3Desc", label: "Card 3 Description", type: "textarea", defaultValue: "Layouts that automatically adapt to any device or viewport." },
  ],
  "features-b": [
    { key: "title", label: "Section Title", type: "text", defaultValue: "How we work" },
    { key: "item1Title", label: "Step 1 Title", type: "text", defaultValue: "Strategy" },
    { key: "item1Desc", label: "Step 1 Description", type: "textarea", defaultValue: "We start with deep research to understand your goals and audience." },
    { key: "item2Title", label: "Step 2 Title", type: "text", defaultValue: "Design" },
    { key: "item2Desc", label: "Step 2 Description", type: "textarea", defaultValue: "Pixel-perfect interfaces built with your brand identity in mind." },
    { key: "item3Title", label: "Step 3 Title", type: "text", defaultValue: "Development" },
    { key: "item3Desc", label: "Step 3 Description", type: "textarea", defaultValue: "Clean, performant code that scales with your business." },
    { key: "item4Title", label: "Step 4 Title", type: "text", defaultValue: "Launch" },
    { key: "item4Desc", label: "Step 4 Description", type: "textarea", defaultValue: "We handle deployment, testing and post-launch support." },
  ],
  "features-c": [
    { key: "badge", label: "Badge Text", type: "text", defaultValue: "Who We Are" },
    { key: "heading", label: "Heading", type: "textarea", defaultValue: "Passionate Creators,\nInnovators, And Visionaries" },
    { key: "subtitle", label: "Subtitle", type: "textarea", defaultValue: "We are a team of visionary creators, strategists, and technologists. With a deep passion for design and a commitment to excellence." },
    { key: "card1Title", label: "Card 1 Title", type: "text", defaultValue: "Client-Centric Approach" },
    { key: "card1Desc", label: "Card 1 Description", type: "textarea", defaultValue: "We listen closely and craft every pixel with your goals in mind, ensuring a tailored and purposeful design." },
    { key: "card2Title", label: "Card 2 Title", type: "text", defaultValue: "Strategic Thinking" },
    { key: "card2Desc", label: "Card 2 Description", type: "textarea", defaultValue: "Every decision is backed by strategy. We ensure Honesta's vision aligns with real business outcomes." },
    { key: "card3Title", label: "Card 3 Title", type: "text", defaultValue: "Creative Excellence" },
    { key: "card3Desc", label: "Card 3 Description", type: "textarea", defaultValue: "From bold visuals to micro-interactions, we pursue creativity that resonates and elevates every touchpoint." },
    { key: "card4Title", label: "Card 4 Title", type: "text", defaultValue: "Timely Delivery" },
    { key: "card4Desc", label: "Card 4 Description", type: "textarea", defaultValue: "We respect your time. Projects are scoped, planned and delivered on schedule without compromising quality." },
  ],
  "features-d": [
    { key: "badge", label: "Badge Text", type: "text", defaultValue: "Services" },
    { key: "heading", label: "Heading", type: "textarea", defaultValue: "Tailored Solutions For\nYour Needs" },
    { key: "subtitle", label: "Subtitle", type: "textarea", defaultValue: "From client-ready app interfaces to user-friendly websites, our team is focused on delivering excellence." },
    { key: "svc1Title", label: "Service 1 Title", type: "text", defaultValue: "Mobile & Website Design" },
    { key: "svc1Desc", label: "Service 1 Description", type: "textarea", defaultValue: "We design beautiful, conversion-focused interfaces for every screen. Each layout is built for clarity, branding alignment and a seamless user journey." },
    { key: "svc2Title", label: "Service 2 Title", type: "text", defaultValue: "Website Development" },
    { key: "svc2Desc", label: "Service 2 Description", type: "textarea", defaultValue: "We develop fast, responsive web applications leveraging modern frameworks to deliver maintainable, scalable code." },
    { key: "svc3Title", label: "Service 3 Title", type: "text", defaultValue: "Brand Guideline" },
    { key: "svc3Desc", label: "Service 3 Description", type: "textarea", defaultValue: "We craft detailed brand guidelines that give you a consistent, professional identity across every touchpoint." },
    { key: "svc4Title", label: "Service 4 Title", type: "text", defaultValue: "Product Design" },
    { key: "svc4Desc", label: "Service 4 Description", type: "textarea", defaultValue: "From concept to finished product, we design purposeful digital tools that solve real problems for your users." },
  ],
  "features-e": [
    { key: "badge", label: "Badge Text", type: "text", defaultValue: "Our Approach" },
    { key: "heading", label: "Heading", type: "textarea", defaultValue: "We Blend Beauty\nAnd Functionality\nSeamlessly" },
    { key: "subtitle", label: "Subtitle", type: "textarea", defaultValue: "Our user-friendly designs make navigating a breeze, ensuring visitors enjoy both seamless experiences and make." },
    { key: "ctaText", label: "CTA Text", type: "text", defaultValue: "Get In Touch Now" },
  ],
  "testimonials-a": [
    { key: "title", label: "Section Title", type: "text", defaultValue: "What people are saying" },
    { key: "quote1", label: "Quote 1", type: "textarea", defaultValue: "This builder completely transformed how we approach our web presence." },
    { key: "author1", label: "Author 1", type: "text", defaultValue: "Alex Chen" },
    { key: "role1", label: "Role 1", type: "text", defaultValue: "Founder, Pixel Co" },
    { key: "quote2", label: "Quote 2", type: "textarea", defaultValue: "The attention to detail is remarkable. Best tool I've used in years." },
    { key: "author2", label: "Author 2", type: "text", defaultValue: "Sarah Kim" },
    { key: "role2", label: "Role 2", type: "text", defaultValue: "Designer, Studio M" },
    { key: "quote3", label: "Quote 3", type: "textarea", defaultValue: "Saved our team weeks of development time. Absolutely worth it." },
    { key: "author3", label: "Author 3", type: "text", defaultValue: "James Okoro" },
    { key: "role3", label: "Role 3", type: "text", defaultValue: "CTO, Launchpad" },
  ],
  "testimonials-b": [
    { key: "title", label: "Section Title", type: "text", defaultValue: "Client Stories" },
    { key: "quote1", label: "Quote 1", type: "textarea", defaultValue: "They delivered beyond our expectations. The attention to craft is unmatched." },
    { key: "author1", label: "Author 1", type: "text", defaultValue: "Maria Reynolds" },
    { key: "role1", label: "Role 1", type: "text", defaultValue: "CEO, Vortex Labs" },
    { key: "quote2", label: "Quote 2", type: "textarea", defaultValue: "Working with this team felt like having an in-house design department." },
    { key: "author2", label: "Author 2", type: "text", defaultValue: "Tom Bradley" },
    { key: "role2", label: "Role 2", type: "text", defaultValue: "Head of Product, Arc" },
  ],
  "testimonials-c": [
    { key: "badge", label: "Badge Text", type: "text", defaultValue: "Testimonials" },
    { key: "title", label: "Section Title", type: "textarea", defaultValue: "What Fast-Growing Teams\nSay About Us" },
    { key: "quote1", label: "Quote 1", type: "textarea", defaultValue: "Is The First Product I've Seen That Customers The Demo Experience They Demand. This Is What Modern GTM Looks Like." },
    { key: "author1", label: "Author 1", type: "text", defaultValue: "Brennan Burke" },
    { key: "role1", label: "Role 1", type: "text", defaultValue: "CEO, Hyperspell" },
    { key: "quote2", label: "Quote 2", type: "textarea", defaultValue: "Hobbes Dramatically Speeds Up Our Process By Getting To A Demo Immediately. It's Far More Engaging And Relevant Than Scrolling Through A Website." },
    { key: "author2", label: "Author 2", type: "text", defaultValue: "Han Gu" },
    { key: "role2", label: "Role 2", type: "text", defaultValue: "Co-Founder & CTO, Palate Insights" },
    { key: "quote3", label: "Quote 3", type: "textarea", defaultValue: "Hobbes Materially Accelerates And Strengthens Our Sales Process To Deliver Deep Personal Demos To Those Who May Not Be Ready To Talk." },
    { key: "author3", label: "Author 3", type: "text", defaultValue: "Joseph Helmy" },
    { key: "role3", label: "Role 3", type: "text", defaultValue: "Founder & CEO, Haukvard" },
    { key: "quote4", label: "Quote 4", type: "textarea", defaultValue: "We replaced three tools with one. The workflow improvement alone paid for itself within the first month of onboarding." },
    { key: "author4", label: "Author 4", type: "text", defaultValue: "Lena Torres" },
    { key: "role4", label: "Role 4", type: "text", defaultValue: "VP Product, Astra Labs" },
    { key: "quote5", label: "Quote 5", type: "textarea", defaultValue: "Our conversion rate jumped 40% after switching. The product just understands what modern teams need to move quickly." },
    { key: "author5", label: "Author 5", type: "text", defaultValue: "Marcus Reid" },
    { key: "role5", label: "Role 5", type: "text", defaultValue: "Head of Growth, Nomad" },
  ],
  "gallery-a": [
    { key: "title", label: "Section Title", type: "text", defaultValue: "Our Work" },
    { key: "subtitle", label: "Subtitle", type: "text", defaultValue: "A selection of projects we're proud of." },
  ],
  "gallery-b": [
    { key: "title", label: "Section Title", type: "text", defaultValue: "Selected Work" },
    { key: "item1Title", label: "Project 1 Name", type: "text", defaultValue: "Brand Refresh" },
    { key: "item1Cat", label: "Project 1 Category", type: "text", defaultValue: "Branding" },
    { key: "item2Title", label: "Project 2 Name", type: "text", defaultValue: "Mobile App" },
    { key: "item2Cat", label: "Project 2 Category", type: "text", defaultValue: "Development" },
    { key: "item3Title", label: "Project 3 Name", type: "text", defaultValue: "E-Commerce" },
    { key: "item3Cat", label: "Project 3 Category", type: "text", defaultValue: "Web Design" },
    { key: "item4Title", label: "Project 4 Name", type: "text", defaultValue: "Dashboard" },
    { key: "item4Cat", label: "Project 4 Category", type: "text", defaultValue: "UI/UX" },
  ],
  "pricing-a": [
    { key: "title", label: "Section Title", type: "text", defaultValue: "Pricing" },
    { key: "plan1Name", label: "Plan 1 Name", type: "text", defaultValue: "Starter" },
    { key: "plan1Price", label: "Plan 1 Price", type: "text", defaultValue: "$19" },
    { key: "plan1Desc", label: "Plan 1 Description", type: "text", defaultValue: "Perfect for personal projects" },
    { key: "plan1Features", label: "Plan 1 Features", type: "list", defaultValue: "1 Website, Basic Analytics, Email Support" },
    { key: "plan2Name", label: "Plan 2 Name", type: "text", defaultValue: "Pro" },
    { key: "plan2Price", label: "Plan 2 Price", type: "text", defaultValue: "$49" },
    { key: "plan2Desc", label: "Plan 2 Description", type: "text", defaultValue: "For growing businesses" },
    { key: "plan2Features", label: "Plan 2 Features", type: "list", defaultValue: "5 Websites, Advanced Analytics, Priority Support, Custom Domain" },
    { key: "plan3Name", label: "Plan 3 Name", type: "text", defaultValue: "Enterprise" },
    { key: "plan3Price", label: "Plan 3 Price", type: "text", defaultValue: "$99" },
    { key: "plan3Desc", label: "Plan 3 Description", type: "text", defaultValue: "For teams at scale" },
    { key: "plan3Features", label: "Plan 3 Features", type: "list", defaultValue: "Unlimited Websites, Full Analytics, Dedicated Manager, SLA Guarantee" },
    { key: "btnText", label: "Button Text", type: "text", defaultValue: "Get Started" },
  ],
  "pricing-b": [
    { key: "title", label: "Section Title", type: "text", defaultValue: "Simple, transparent pricing" },
    { key: "subtitle", label: "Subtitle", type: "text", defaultValue: "No hidden fees. Cancel anytime." },
    { key: "plan1Name", label: "Plan 1 Name", type: "text", defaultValue: "Basic" },
    { key: "plan1Price", label: "Plan 1 Price", type: "text", defaultValue: "$29" },
    { key: "plan1Features", label: "Plan 1 Features", type: "list", defaultValue: "Up to 3 pages, Mobile responsive, Basic SEO, Email support" },
    { key: "plan2Name", label: "Plan 2 Name", type: "text", defaultValue: "Growth" },
    { key: "plan2Price", label: "Plan 2 Price", type: "text", defaultValue: "$79" },
    { key: "plan2Features", label: "Plan 2 Features", type: "list", defaultValue: "Up to 15 pages, Advanced SEO, Analytics dashboard, Priority support, Custom integrations" },
    { key: "plan3Name", label: "Plan 3 Name", type: "text", defaultValue: "Scale" },
    { key: "plan3Price", label: "Plan 3 Price", type: "text", defaultValue: "$149" },
    { key: "plan3Features", label: "Plan 3 Features", type: "list", defaultValue: "Unlimited pages, Dedicated account manager, Custom API access, White-label option, SLA guarantee, 24/7 phone support" },
    { key: "btnText", label: "Button Text", type: "text", defaultValue: "Get Started" },
  ],
  "pricing-c": [
    { key: "heading", label: "Heading", type: "text", defaultValue: "Pricing" },
    { key: "subtitle", label: "Subtitle", type: "textarea", defaultValue: "Simple, transparent pricing for every stage of your business." },
    { key: "plan1Label", label: "Plan 1 Label", type: "text", defaultValue: "STARTER" },
    { key: "plan1Name", label: "Plan 1 Name", type: "text", defaultValue: "Website Development" },
    { key: "plan1Price", label: "Plan 1 Price", type: "text", defaultValue: "$2,500" },
    { key: "plan1Desc", label: "Plan 1 Description", type: "text", defaultValue: "Perfect for businesses looking for a professional online presence." },
    { key: "plan1Features", label: "Plan 1 Features", type: "list", defaultValue: "Custom Design, Responsive Layout, SEO Optimized, CMS Integration, 3 Revisions" },
    { key: "plan2Label", label: "Plan 2 Label", type: "text", defaultValue: "PROFESSIONAL" },
    { key: "plan2Name", label: "Plan 2 Name", type: "text", defaultValue: "App Development" },
    { key: "plan2Price", label: "Plan 2 Price", type: "text", defaultValue: "$8,000" },
    { key: "plan2Desc", label: "Plan 2 Description", type: "text", defaultValue: "Full-scale application development for iOS, Android, or web platforms." },
    { key: "plan2Features", label: "Plan 2 Features", type: "list", defaultValue: "Cross-Platform, Custom Backend, User Authentication, Push Notifications, Analytics Dashboard, Ongoing Support" },
    { key: "plan3Label", label: "Plan 3 Label", type: "text", defaultValue: "ESSENTIAL" },
    { key: "plan3Name", label: "Plan 3 Name", type: "text", defaultValue: "Hosting & Maintenance" },
    { key: "plan3Price", label: "Plan 3 Price", type: "text", defaultValue: "$50/mo" },
    { key: "plan3Desc", label: "Plan 3 Description", type: "text", defaultValue: "Reliable hosting and ongoing maintenance to keep your product running smoothly." },
    { key: "plan3Features", label: "Plan 3 Features", type: "list", defaultValue: "99.9% Uptime, SSL Certificate, Daily Backups, Performance Monitoring" },
    { key: "btnText", label: "Button Text", type: "text", defaultValue: "Get Started" },
  ],
  "faq-a": [
    { key: "q1", label: "Question 1", type: "text", defaultValue: "How do I get started?" },
    { key: "a1", label: "Answer 1", type: "textarea", defaultValue: "Sign up for a free account and choose a template to begin building your website." },
    { key: "q2", label: "Question 2", type: "text", defaultValue: "Can I use my own domain?" },
    { key: "a2", label: "Answer 2", type: "textarea", defaultValue: "Yes, all Pro and Enterprise plans include custom domain support." },
    { key: "q3", label: "Question 3", type: "text", defaultValue: "Is there a free trial?" },
    { key: "a3", label: "Answer 3", type: "textarea", defaultValue: "We offer a 14-day free trial on all paid plans, no credit card required." },
    { key: "q4", label: "Question 4", type: "text", defaultValue: "Do you offer refunds?" },
    { key: "a4", label: "Answer 4", type: "textarea", defaultValue: "Yes, we have a 30-day money-back guarantee on all plans." },
  ],
  "faq-b": [
    { key: "title", label: "Section Title", type: "textarea", defaultValue: "Questions?\nWe've got answers." },
    { key: "q1", label: "Question 1", type: "text", defaultValue: "What is included in the free trial?" },
    { key: "a1", label: "Answer 1", type: "textarea", defaultValue: "Full access to all features for 14 days. No credit card required." },
    { key: "q2", label: "Question 2", type: "text", defaultValue: "Can I cancel at any time?" },
    { key: "a2", label: "Answer 2", type: "textarea", defaultValue: "Absolutely. There are no long-term contracts and you can cancel with one click." },
    { key: "q3", label: "Question 3", type: "text", defaultValue: "Do you offer custom plans?" },
    { key: "a3", label: "Answer 3", type: "textarea", defaultValue: "Yes — for teams of 10+ we can create a bespoke package tailored to your needs." },
    { key: "q4", label: "Question 4", type: "text", defaultValue: "How do I migrate my existing site?" },
    { key: "a4", label: "Answer 4", type: "textarea", defaultValue: "Our onboarding team will handle the full migration at no extra cost." },
    { key: "q5", label: "Question 5", type: "text", defaultValue: "Is there a setup fee?" },
    { key: "a5", label: "Answer 5", type: "textarea", defaultValue: "No setup fees on any plan. You only pay the monthly or annual subscription." },
  ],
  "faq-c": [
    { key: "heading", label: "Heading", type: "text", defaultValue: "Frequently Asked Questions" },
    { key: "subtitle", label: "Subtitle", type: "textarea", defaultValue: "Everything you need to know about working with us." },
    { key: "q1", label: "Question 1", type: "text", defaultValue: "What services do you offer?" },
    { key: "a1", label: "Answer 1", type: "textarea", defaultValue: "We specialize in building custom web applications, mobile apps, and robust backend systems tailored to scale with your business." },
    { key: "q2", label: "Question 2", type: "text", defaultValue: "How long does a typical project take?" },
    { key: "a2", label: "Answer 2", type: "textarea", defaultValue: "Project timelines vary depending on complexity. A standard website might take 4-6 weeks, while complex applications can take 3-6 months." },
    { key: "q3", label: "Question 3", type: "text", defaultValue: "What is your typical tech stack?" },
    { key: "a3", label: "Answer 3", type: "textarea", defaultValue: "We primarily work with Next.js, TypeScript, and Node.js for scalability, though we choose the best tools for each project." },
    { key: "q4", label: "Question 4", type: "text", defaultValue: "Do you offer ongoing maintenance and support?" },
    { key: "a4", label: "Answer 4", type: "textarea", defaultValue: "Yes, we provide flexible support and hosting plans to ensure your digital products stay secure, up-to-date, and high-performing." },
    { key: "q5", label: "Question 5", type: "text", defaultValue: "Can you help with app store submissions?" },
    { key: "a5", label: "Answer 5", type: "textarea", defaultValue: "Absolutely. We handle the entire deployment process, including Apple App Store and Google Play Store submissions." },
    { key: "q6", label: "Question 6", type: "text", defaultValue: "How do you handle project security?" },
    { key: "a6", label: "Answer 6", type: "textarea", defaultValue: "Security is built into our architecture from day one. We follow industry best practices for data encryption and secure authentication." },
  ],
  "cta-bold": [
    { key: "heading",     label: "Heading",           type: "text",     defaultValue: "STAY IN\nTHE LOOP" },
    { key: "placeholder", label: "Input Placeholder",  type: "text",     defaultValue: "Enter your email" },
    { key: "btnText",     label: "Button Text",        type: "text",     defaultValue: "Subscribe" },
    { key: "subtext",     label: "Subtext",            type: "text",     defaultValue: "No spam. Unsubscribe anytime." },
  ],
  "cta-centered": [
    { key: "eyebrow",     label: "Eyebrow Label",    type: "text",     defaultValue: "Get Started" },
    { key: "heading",    label: "Heading",           type: "text",     defaultValue: "Start building something great today" },
    { key: "description",label: "Description",       type: "textarea", defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore." },
    { key: "primaryBtn", label: "Primary Button",    type: "text",     defaultValue: "Get Started" },
    { key: "secondaryBtn",label: "Secondary Button", type: "text",     defaultValue: "Learn More" },
  ],
  "cta-flat": [
    { key: "eyebrow",     label: "Eyebrow Label",    type: "text",     defaultValue: "Get Started" },
    { key: "heading",     label: "Heading",           type: "text",     defaultValue: "Ready to bring your vision to life?" },
    { key: "description", label: "Description",       type: "textarea", defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore." },
    { key: "primaryBtn",  label: "Primary Button",    type: "text",     defaultValue: "Get Started" },
    { key: "secondaryBtn",label: "Secondary Button",  type: "text",     defaultValue: "Learn More" },
  ],
  "cta-split": [
    { key: "eyebrow",      label: "Eyebrow Label",      type: "text",     defaultValue: "Why Us" },
    { key: "heading",      label: "Heading",            type: "text",     defaultValue: "Solutions for Every Need" },
    { key: "feature1Title",label: "Feature 1 Title",    type: "text",     defaultValue: "Fast Setup" },
    { key: "feature1Desc", label: "Feature 1 Description", type: "textarea", defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit." },
    { key: "feature2Title",label: "Feature 2 Title",    type: "text",     defaultValue: "Reliable" },
    { key: "feature2Desc", label: "Feature 2 Description", type: "textarea", defaultValue: "Ut enim ad minim veniam, quis nostrud exercitation ullamco." },
    { key: "primaryBtn",   label: "Primary Button",     type: "text",     defaultValue: "Get Started" },
    { key: "secondaryBtn", label: "Secondary Button",   type: "text",     defaultValue: "Learn More" },
    { key: "imageUrl",     label: "Image URL (optional)", type: "text",   defaultValue: "" },
  ],
  "cta-split-flipped": [
    { key: "eyebrow",      label: "Eyebrow Label",         type: "text",     defaultValue: "Our Offer" },
    { key: "heading",      label: "Heading",               type: "text",     defaultValue: "Built for Scale, Designed for You" },
    { key: "feature1Title",label: "Feature 1 Title",       type: "text",     defaultValue: "Performance" },
    { key: "feature1Desc", label: "Feature 1 Description", type: "textarea", defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit." },
    { key: "feature2Title",label: "Feature 2 Title",       type: "text",     defaultValue: "Reliability" },
    { key: "feature2Desc", label: "Feature 2 Description", type: "textarea", defaultValue: "Duis aute irure dolor in reprehenderit in voluptate velit." },
    { key: "primaryBtn",   label: "Primary Button",        type: "text",     defaultValue: "Get Started" },
    { key: "secondaryBtn", label: "Secondary Button",      type: "text",     defaultValue: "Learn More" },
    { key: "imageUrl",     label: "Image URL (optional)",  type: "text",     defaultValue: "" },
  ],
  "cta-gradient": [
    { key: "heading", label: "Heading",      type: "textarea", defaultValue: "Clarity, structure, and speed for your workflow" },
    { key: "btnText", label: "Button Text",  type: "text",     defaultValue: "Get Started" },
  ],
  "cta-dark-banner": [
    { key: "heading",     label: "Heading",            type: "textarea", defaultValue: "Take the next step toward a better experience" },
    { key: "subheading",  label: "Subheading",         type: "textarea", defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod." },
    { key: "primaryBtn",  label: "Primary Button",     type: "text",     defaultValue: "Get Started" },
    { key: "secondaryBtn",label: "Secondary Button",   type: "text",     defaultValue: "Learn More" },
  ],
  "cta-immersive": [
    { key: "heading",     label: "Heading",            type: "text",     defaultValue: "Let's build something great together" },
    { key: "description", label: "Description",        type: "textarea", defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Get in touch to start your next project." },
    { key: "primaryBtn",  label: "Primary Button",     type: "text",     defaultValue: "Get Started" },
    { key: "secondaryBtn",label: "Secondary Button",   type: "text",     defaultValue: "Learn More" },
  ],
  "footer-classic": [
    { key: "logo", label: "Logo Text", type: "text", defaultValue: "Brand" },
    { key: "tagline", label: "Tagline", type: "textarea", defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod." },
    { key: "col1Title", label: "Column 1 Title", type: "text", defaultValue: "Pages" },
    { key: "col1Links", label: "Column 1 Links", type: "list", defaultValue: "Home, About, Services, Pricing, Contact" },
    { key: "col2Title", label: "Column 2 Title", type: "text", defaultValue: "Company" },
    { key: "col2Links", label: "Column 2 Links", type: "list", defaultValue: "About, Team, Careers, Blog" },
    { key: "col3Title", label: "Column 3 Title", type: "text", defaultValue: "Support" },
    { key: "col3Links", label: "Column 3 Links", type: "list", defaultValue: "Help, Contact, FAQ" },
    { key: "copyright", label: "Copyright", type: "text", defaultValue: "\u00a9 2025 Brand. All rights reserved." },
  ],
  "footer-minimal": [
    { key: "logoText", label: "Logo Text", type: "text", defaultValue: "Brand" },
    { key: "tagline", label: "Tagline", type: "text", defaultValue: "Questions or feedback? Get in touch." },
    { key: "email", label: "Email", type: "text", defaultValue: "hello@example.com" },
    { key: "phone", label: "Phone", type: "text", defaultValue: "+1 234 567 890" },
    { key: "navLinks", label: "Nav Links", type: "list", defaultValue: "Home, About, Services, Pricing, Contact" },
    { key: "resourceLinks", label: "Resource Links", type: "list", defaultValue: "Blog, Guides, Docs, Support" },
    { key: "supportLinks", label: "Support Links", type: "list", defaultValue: "FAQ, Contact, Terms, Privacy" },
    { key: "copyright", label: "Copyright", type: "text", defaultValue: "\u00a9 2025 Brand. All rights reserved." },
  ],
  "footer-spinny": [
    { key: "navItems", label: "Nav Items", type: "list", defaultValue: "HOME, ABOUT, SERVICES, WORK, BLOG, FAQ, CONTACT" },
    { key: "copyright", label: "Copyright", type: "text", defaultValue: "\u00a9 2025. All Rights Reserved." },
    { key: "legalText", label: "Legal Link Text", type: "text", defaultValue: "LEGAL" },
  ],
  "footer-bigname": [
    { key: "logo", label: "Brand Name", type: "text", defaultValue: "Brand" },
    { key: "tagline", label: "Tagline", type: "text", defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit." },
    { key: "col1Title", label: "Column 1 Title", type: "text", defaultValue: "Pages" },
    { key: "col1Links", label: "Column 1 Links", type: "list", defaultValue: "Home, About, Services, Pricing, Contact" },
    { key: "col2Title", label: "Column 2 Title", type: "text", defaultValue: "Company" },
    { key: "col2Links", label: "Column 2 Links", type: "list", defaultValue: "Blog, Careers, Press, Contact" },
    { key: "socialLinks", label: "Social Links", type: "list", defaultValue: "Instagram, X, Facebook, LinkedIn, TikTok" },
    { key: "copyright", label: "Copyright", type: "text", defaultValue: "\u00a9 2025 Brand. All rights reserved." },
  ],
  "footer-immersive": [
    { key: "logo", label: "Logo Text", type: "text", defaultValue: "Brand" },
    { key: "tagline", label: "Top Tagline", type: "text", defaultValue: "Build fast. Ship often." },
    { key: "brandName", label: "Large Brand Name", type: "text", defaultValue: "Brand" },
    { key: "col1Title", label: "Column 1 Title", type: "text", defaultValue: "Menu" },
    { key: "col1Links", label: "Column 1 Links", type: "list", defaultValue: "Home, About, Services, Pricing, Contact" },
    { key: "col2Title", label: "Column 2 Title", type: "text", defaultValue: "Socials" },
    { key: "col2Links", label: "Column 2 Links", type: "list", defaultValue: "Instagram, X, Facebook, LinkedIn, TikTok" },
    { key: "col3Title", label: "Column 3 Title", type: "text", defaultValue: "Resources" },
    { key: "col3Links", label: "Column 3 Links", type: "list", defaultValue: "Blog, Newsletter, Docs" },
  ],
  "footer-corporate": [
    { key: "logo", label: "Logo / Brand Name", type: "text", defaultValue: "Brand" },
    { key: "tagline", label: "Tagline", type: "textarea", defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt." },
    { key: "col1Title", label: "Column 1 Title", type: "text", defaultValue: "Pages" },
    { key: "col1Links", label: "Column 1 Links", type: "list", defaultValue: "Home, About, Services, Pricing, Contact" },
    { key: "col2Title", label: "Column 2 Title", type: "text", defaultValue: "Resources" },
    { key: "col2Links", label: "Column 2 Links", type: "list", defaultValue: "Blog, Docs, Newsletter, Guides" },
    { key: "col3Title", label: "Column 3 Title", type: "text", defaultValue: "Company" },
    { key: "col3Links", label: "Column 3 Links", type: "list", defaultValue: "About, Careers, Press, Partners" },
    { key: "copyright", label: "Copyright", type: "text", defaultValue: "\u00a9 2025 Brand. All rights reserved." },
    { key: "legal1", label: "Legal Link 1", type: "text", defaultValue: "Terms of Service" },
    { key: "legal2", label: "Legal Link 2", type: "text", defaultValue: "Privacy Policy" },
  ],
  "stats-a": [
    { key: "label", label: "Label (above stats)", type: "text", defaultValue: "Trusted by teams worldwide" },
    { key: "stat1Value", label: "Stat 1 Value", type: "text", defaultValue: "500+" },
    { key: "stat1Label", label: "Stat 1 Label", type: "text", defaultValue: "Happy Clients" },
    { key: "stat2Value", label: "Stat 2 Value", type: "text", defaultValue: "99.9%" },
    { key: "stat2Label", label: "Stat 2 Label", type: "text", defaultValue: "Uptime SLA" },
    { key: "stat3Value", label: "Stat 3 Value", type: "text", defaultValue: "2M+" },
    { key: "stat3Label", label: "Stat 3 Label", type: "text", defaultValue: "Requests / Day" },
    { key: "stat4Value", label: "Stat 4 Value", type: "text", defaultValue: "24/7" },
    { key: "stat4Label", label: "Stat 4 Label", type: "text", defaultValue: "Support" },
  ],
  "logobanner-a": [
    { key: "label", label: "Label text", type: "text", defaultValue: "Trusted by leading companies" },
    { key: "logo1", label: "Company 1", type: "text", defaultValue: "Stripe" },
    { key: "logo2", label: "Company 2", type: "text", defaultValue: "Vercel" },
    { key: "logo3", label: "Company 3", type: "text", defaultValue: "Linear" },
    { key: "logo4", label: "Company 4", type: "text", defaultValue: "Supabase" },
    { key: "logo5", label: "Company 5", type: "text", defaultValue: "Figma" },
    { key: "logo6", label: "Company 6", type: "text", defaultValue: "Notion" },
  ],
};

/** Get the content schema for a given variant ID */
export const getContentSchema = (variantId: string): ContentField[] | null => {
  return variantContentSchemas[variantId] ?? null;
};
